# Not yet Tuned
PuddleWorld-v0:
  n_envs: 8
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.8
  gamma: 1
  n_epochs: 20
  ent_coef: 0.0
  learning_rate: lin_0.01
  clip_range: lin_0.2
  policy_kwargs: "dict(net_arch=[32, 32])"

NoPuddleWorldStochastic-v0:
  n_envs: 16
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  n_steps: 32
  batch_size: 512
  gae_lambda: 0.8
  gamma: 0.98
  n_epochs: 20
  ent_coef: 0.0
  learning_rate: lin_0.001
  clip_range: lin_0.2
